default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  collation: utf8_bin

development:
  <<: *default
  database: autocargo_development
  socket: /tmp/mysql.sock
  username: root
  password: kaosbite

test:
  <<: *default
  database: autocargo_test
  socket: /tmp/mysql.sock
  username: root
  password: kaosbite

production:
  <<: *default
  database: c1autocargo
  username: c1autocargo
  password: BGKri6OhFjtFI
